data:
  products:
    - id: 1
      name: Chocolate - Supermilk
      description: Duis bibendum
      price: '78.61'
    - id: 2
      name: Cream - Double
      description: Donec semper sapien a libero
      price: '4.50'
    - id: 3
      name: Salmon Atlantic Whole
      description: Suspendisse potenti
      price: '77.22'
    - id: 4
      name: Cheese - La Sauvagne
      description: Morbi a ipsum
      price: '74.00'
    - id: 5
      name: Onions - Red
      description: Nullam molestie nibh in lectus
      price: '95.42'
    - id: 6
      name: Wine - Buckfast
      description: Ut at dolor quis odio consequat varius
      price: '25.99'
    - id: 7
      name: Beef - Ribeye
      description: Aenean lectus
      price: '53.02'
    - id: 8
      name: Pike - Frozen Fillet
      description: Nunc nisl
      price: '96.35'
    - id: 9
      name: Orange - Seville, Thick Cut
      description: In hac habitasse platea dictumst
      price: '91.00'
    - id: 10
      name: Puff Pastry - Sheets
      description: Nunc purus
      price: '70.44'
    - id: 11
      name: Ham - Cooked Bayonne Tinned
      description: In blandit ultrices enim
      price: '14.71'
    - id: 12
      name: Sunflower Seed Raw
      description: Etiam pretium iaculis justo
      price: '99.90'
    - id: 13
      name: Raisin - Dark
      description: Cum sociis natoque penatibus et magnis dis parturient montes, nascetur
        ridiculus mus
      price: '44.95'
    - id: 14
      name: Cinnamon - Ground
      description: Duis bibendum
      price: '91.42'
    - id: 15
      name: Sprouts - China Rose
      description: Fusce consequat
      price: '63.84'
    - id: 16
      name: Mushroom - Chanterelle, Fresh
      description: Phasellus in felis
      price: '39.91'
    - id: 17
      name: Rye Special Old
      description: Suspendisse potenti
      price: '71.11'
    - id: 18
      name: Mousse - Banana Chocolate
      description: Curabitur convallis
      price: '40.60'
    - id: 19
      name: Cheese - Brie
      description: Aenean lectus
      price: '59.57'
    - id: 20
      name: Pepper - Jalapeno
      description: Morbi non lectus
      price: '6.39'
    - id: 21
      name: Savory
      description: Aenean fermentum
      price: '47.50'
    - id: 22
      name: Chocolate - White Cooking
      description: Cras non velit nec nisi vulputate nonummy
      price: '10.63'
    - id: 23
      name: Tea - Darjeeling, First Flush
      description: Cum sociis natoque penatibus et magnis dis parturient montes, nascetur
        ridiculus mus
      price: '67.01'
    - id: 24
      name: Wine - Amarone
      description: Morbi non lectus
      price: '39.66'
    - id: 25
      name: Chocolate - Dark Truffles
      description: Integer aliquet, massa id lobortis convallis, tortor risus dapibus
        augue, vel accumsan tellus nisi eu orci
      price: '40.70'
    - id: 26
      name: Bread - Sourdough
      description: In hac habitasse platea dictumst
      price: '34.55'
    - id: 27
      name: Wine - Alsace Gewurztraminer
      description: Maecenas ut massa quis augue luctus tincidunt
      price: '15.48'
    - id: 28
      name: Soup - Cream Of Broccoli
      description: Nulla ut erat id mauris vulputate elementum
      price: '74.18'
    - id: 29
      name: Shrimp - Freshwater
      description: Nullam sit amet turpis elementum ligula vehicula consequat
      price: '48.78'
    - id: 30
      name: Cheese - Cheddar With Claret
      description: Morbi a ipsum
      price: '96.47'
    - id: 31
      name: Whisky - Single Malt, Talisker 57 North
      description: Duis at velit eu est congue elementum
      price: '74.13'
    - id: 32
      name: Aubergine - Regular
      description: Vivamus vel nulla eget eros elementum pellentesque
      price: '71.83'
    - id: 33
      name: Tart Shells - Sweet, 3
      description: Quisque porta volutpat erat
      price: '85.04'
    - id: 34
      name: Ecolab - Balanced Fusion
      description: Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam
      price: '62.14'
    - id: 35
      name: Ketchup - Tomato
      description: In quis justo
      price: '4.81'
    - id: 36
      name: Coffee - Dolce Gusto, Capsules x20
      description: Nulla facilisi
      price: '88.05'
    - id: 37
      name: Frangelico
      description: Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis
      price: '95.88'
    - id: 38
      name: Bread - 10 Grain Parisian
      description: Proin eu mi
      price: '58.63'
    - id: 39
      name: Energy Drink - Red Bull
      description: Morbi quis tortor id nulla ultrices aliquet
      price: '60.34'
    - id: 40
      name: Galliano
      description: Donec semper sapien a libero
      price: '88.45'
    - id: 41
      name: Cheese Cloth No 60
      description: Nulla nisl
      price: '27.94'
    - id: 42
      name: Crab - Back Fin Meat, Canned
      description: Aliquam quis turpis eget elit sodales scelerisque
      price: '56.64'
    - id: 43
      name: Aubergine - Asian
      description: Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede
      price: '67.26'
    - id: 44
      name: Pie Shell - 5
      description: Nullam molestie nibh in lectus
      price: '68.57'
    - id: 45
      name: Bread - Roll, Italian
      description: Vivamus vel nulla eget eros elementum pellentesque
      price: '28.97'
    - id: 46
      name: Carrots - Purple, Organic
      description: Etiam vel augue
      price: '79.08'
    - id: 47
      name: Foie Gras
      description: Mauris lacinia sapien quis libero
      price: '17.10'
    - id: 48
      name: Magnotta - Bel Paese White
      description: Aenean lectus
      price: '37.03'
    - id: 49
      name: Cabbage Roll
      description: In hac habitasse platea dictumst
      price: '25.65'
    - id: 50
      name: Clams - Bay
      description: Cum sociis natoque penatibus et magnis dis parturient montes, nascetur
        ridiculus mus
      price: '27.96'
    - id: 51
      name: Yogurt - Strawberry, 175 Gr
      description: Praesent blandit
      price: '28.65'
    - id: 52
      name: Lemonade - Cloudy
      description: Nullam varius
      price: '51.32'
    - id: 53
      name: Flour - Wholemeal Rye
      description: Nulla facilisi
      price: '40.38'
    - id: 54
      name: Lemon Balm - Fresh
      description: Nam dui
      price: '71.33'
    - id: 55
      name: Turnip - White, Organic
      description: Donec ut dolor
      price: '23.23'
    - id: 56
      name: Iced Tea - Lemon, 460 Ml
      description: Etiam faucibus cursus urna
      price: '50.01'
    - id: 57
      name: Mushroom - Morel Frozen
      description: Integer ac leo
      price: '90.72'
    - id: 58
      name: Bandage - Finger Cots
      description: Aliquam erat volutpat
      price: '96.52'
    - id: 59
      name: Pasta - Linguine
      description: Suspendisse potenti
      price: '78.28'
    - id: 60
      name: Beans - Pinto, Dried
      description: Integer a nibh
      price: '51.91'
    - id: 61
      name: Wine - Savigny - Les Beaune
      description: Duis aliquam convallis nunc
      price: '8.39'
    - id: 62
      name: Muffin Carrot - Individual
      description: Proin at turpis a pede posuere nonummy
      price: '21.88'
    - id: 63
      name: Cinnamon Rolls
      description: Integer ac neque
      price: '17.44'
    - id: 64
      name: Cheese - Brick With Pepper
      description: Vestibulum quam sapien, varius ut, blandit non, interdum in, ante
      price: '75.88'
    - id: 65
      name: Flour - Chickpea
      description: Cras in purus eu magna vulputate luctus
      price: '34.14'
    - id: 66
      name: Longos - Assorted Sandwich
      description: Praesent lectus
      price: '72.05'
    - id: 67
      name: Scrubbie - Scotchbrite Hand Pad
      description: In congue.
      price: '3.53'
    - id: 68
      name: Ostrich - Fan Fillet
      description: Duis aliquam convallis nunc
      price: '57.77'
    - id: 69
      name: Soup - Campbells, Minestrone
      description: In hac habitasse platea dictumst
      price: '64.87'
    - id: 70
      name: Carbonated Water - Blackcherry
      description: Ut at dolor quis odio consequat varius
      price: '74.06'
    - id: 71
      name: Creme De Menthe Green
      description: Nulla neque libero, convallis eget, eleifend luctus, ultricies eu,
        nibh
      price: '62.47'
    - id: 72
      name: Wine - Touraine Azay - Le - Rideau
      description: Aenean lectus
      price: '14.25'
    - id: 73
      name: Wine - Pinot Grigio Collavini
      description: In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem,
        vitae mattis nibh ligula nec sem
      price: '34.80'
    - id: 74
      name: Appetizer - Seafood Assortment
      description: In hac habitasse platea dictumst
      price: '14.15'
    - id: 75
      name: Beef - Texas Style Burger
      description: Praesent id massa id nisl venenatis lacinia
      price: '46.01'
    - id: 76
      name: Wine - Shiraz Wolf Blass Premium
      description: Morbi quis tortor id nulla ultrices aliquet
      price: '34.85'
    - id: 77
      name: Puree - Passion Fruit
      description: Pellentesque ultrices mattis odio
      price: '48.37'
    - id: 78
      name: Lemonade - Island Tea, 591 Ml
      description: Suspendisse ornare consequat lectus
      price: '62.93'
    - id: 79
      name: Beef Ground Medium
      description: Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo
      price: '82.30'
    - id: 80
      name: Chilli Paste, Sambal Oelek
      description: Vestibulum sed magna at nunc commodo placerat
      price: '90.40'
    - id: 81
      name: Pastry - French Mini Assorted
      description: Vestibulum ac est lacinia nisi venenatis tristique
      price: '13.42'
    - id: 82
      name: Coffee - Colombian, Portioned
      description: Nulla mollis molestie lorem
      price: '78.11'
    - id: 83
      name: Soup - Boston Clam Chowder
      description: Curabitur at ipsum ac tellus semper interdum
      price: '76.04'
    - id: 84
      name: Sauce - Apple, Unsweetened
      description: Nulla facilisi
      price: '2.81'
    - id: 85
      name: Kellogs All Bran Bars
      description: Cras non velit nec nisi vulputate nonummy
      price: '51.37'
    - id: 86
      name: Pork - Back, Long Cut, Boneless
      description: Donec ut dolor
      price: '31.85'
    - id: 87
      name: Shortbread - Cookie Crumbs
      description: Phasellus id sapien in sapien iaculis congue
      price: '87.40'
    - id: 88
      name: Glucose
      description: Phasellus sit amet erat
      price: '47.55'
    - id: 89
      name: Pork - Shoulder
      description: In hac habitasse platea dictumst
      price: '32.32'
    - id: 90
      name: Pop Shoppe Cream Soda
      description: Nulla ut erat id mauris vulputate elementum
      price: '4.66'
    - id: 91
      name: Pie Shells 10
      description: Quisque porta volutpat erat
      price: '38.49'
    - id: 92
      name: Sponge Cake Mix - Vanilla
      description: Donec semper sapien a libero
      price: '12.58'
    - id: 93
      name: Pastry - Apple Muffins - Mini
      description: Nullam porttitor lacus at turpis
      price: '76.26'
    - id: 94
      name: Oil - Truffle, White
      description: Donec dapibus
      price: '79.69'
    - id: 95
      name: Cookies - Oatmeal Raisin
      description: Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros
      price: '19.83'
    - id: 96
      name: Cheese - Red Leicester
      description: Maecenas rhoncus aliquam lacus
      price: '50.48'
    - id: 97
      name: Crackers - Multigrain
      description: Nullam porttitor lacus at turpis
      price: '22.50'
    - id: 98
      name: Bread - Hot Dog Buns
      description: Integer non velit
      price: '67.40'
    - id: 99
      name: Dark Chocolate - 1Kg
      description: Donec quis orci eget orci vehicula condimentum
      price: '36.06'
    - id: 100
      name: Flavouring - Orange
      description: Praesent blandit lacinia erat
      price: '57.31'
